### PR TITLE
Update to version 3.2.1 beta 

### PR DESCRIPTION
**Pull request by manijak**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-webgrabplus/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Update Webgrabplus version to 3.2.1 beta

## Benefits of this PR and context:

New version with a critical fix to random crashes that have been present since 3.1.7. 

## How Has This Been Tested?

N/A

## Source / References:

http://webgrabplus.com/download/sw/v3.2.1
http://webgrabplus.com/content/important-urgent-notice

### CODE REVIEW

**Comment by manijak** [comment]
Really not sure why it is still called V3.1.8-pkg 🤔

**Comment by aptalca** [comment]
> Really not sure why it is still called V3.1.8-pkg 🤔

because the jenkinsfile isn't updated: https://github.com/manijak/docker-webgrabplus/blob/master/Jenkinsfile#L106
you would have to run the jenkins-builder to update it, but it still wouldn't work in this PR because jenkins ignores jenkinsfiles changes in PR builds from unauthorized users lol

If you built it locally and it works, please confirm. Then we'll merge and it will be corrected during template updates

**Comment by manijak** [comment]
Yeah the contributing guideline stated to avoid updating the Jenkinsfile and the readme. 
Sorry I haven’t built it locally no, as I don’t have the environment setup, would take me a while to do so.

**Comment by manijak** [comment]
Is there a way I can just fetch the artifact from this last jenkins build and test it on my local docker station?

**Comment by Roxedus** [comment]
Yup! The CI bot pushes the results of prs to dockerhub, this one is at `lspipepr/webgrabplus:V3.1.8-pkg-39139a33-pr-44 `

**Comment by manijak** [comment]
Alright, build seem to work fine localy 👍 
C15DA265-1C07-4E7B-991D-5C80133EB4FF

**Review by aptalca — APPROVED** [review]

**Pull request merged**
