### PR TITLE
Add mono web request library

### PR DESCRIPTION
**Pull request by Alexdc-12**
Addition of libmono-system-net-http-webrequest4.0-cil to resolve issue #22 
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

 

------------------------------

We welcome all PR’s though this doesn’t guarantee it will be accepted.

## Description:
Addition of package libmono-system-net-http-webrequest4.0-cil

## Benefits of this PR and context:
Fixes issue with webgrabb no longer functioning after docker upgrade to v 3.1

## How Has This Been Tested?
Installed in docker and run.

## Source / References:
Issue #22 
http://www.webgrabplus.com/content/critcal-error

### CODE REVIEW

**Comment by tobbenb** [comment]
Please delete the package.txt as that is only used by our build system, so no need to edit it.

**Comment by Alexdc-12** [comment]
Deleted as requested

**Comment by CHBMB** [comment]
@Alexdc-12 LGTM.  Only issue is the formatting of the changes.  Two (minor) issues.

1. `libmono-system-net-http-webrequest4.0-cil \` should be in alphabetical number (ie above libmono-system-web4.0-cil)
2.  Should be indented the same amount as the other lines.

Like I said minor cosmetic issues, as an aside there's no need to edit `README.md` either as that is automatically produced from `readme-vars.yml` but it isn't a problem if you've already edited it, and wouldn't stop a merge.

Definitely getting there!

**Comment by Alexdc-12** [comment]
Not bad for a first attempt! Do i need to change it?

**Comment by CHBMB** [comment]
> Not bad for a first attempt! Do i need to change it?

No, I've submitted a PR to your repository, so if you merge that to your repo, it will fix it, then that change will be reflected here.

Started to feel a bit sorry for you mate!

**Pull request merged**
