### PR TITLE
Update to resolve missing netstandards.dll for v3.1.8

### LINKED ISSUE #42: v3.1.8 'netstandard' error
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

When running the latest compiled docker I get an error message :
```
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'WG.Common.InvalidSyntaxException:_MessageList' (3) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'WG.Common.InvalidSyntaxException:_MessageList' (3) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
```

The process will not run and therefore v.3.1.8 is currently broken.

I have also raise on webgrabplus forum : http://webgrabplus.com/content/v-318-netstandard-error

------------------------------

## Expected Behavior
standard process to run as normal.

## Current Behavior
error message

## Steps to Reproduce
1. run docker for v3.1.8
2. exec into the docker
3. run: `/bin/bash /defaults/update.sh`
4. see error

## Environment
**OS:** Ubuntu 20.4 LTS running docker
**CPU architecture:** x86_64
**How docker service was installed:** Official docker script and loaded docker-compose on top.

## Command used to create docker container (run/create/compose/screenshot)
```
  webgrabplus:
    image: linuxserver/webgrabplus:latest
    container_name: webgrabplus
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/webgrabplus:/config
      - /opt/tvheadend/data:/data
    restart: unless-stopped
```

### PR DESCRIPTION
**Pull request by pbathuk**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-webgrabplus/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Added mono-devel (hopefully in the right format) to resolve the missing netstandards.dll

## Benefits of this PR and context:
fixes #42 
ensures that the v3.1.8 can be used

## How Has This Been Tested?
updated the docker with mono-devel and that resolved the error (also tried other packages but they did not)
I have NOT tested this in the build process, as I am unsure how I would do that. so hopefully the jenkins build will fail if I have done something incorrect

## Source / References:
#42

### CODE REVIEW

**Comment by pbathuk** [comment]
Just to flag - and I have not used autochecks / jenkins previously - but the Package info does not show the mono-devel that I added.. but not sure if that is expected or not.

**Review by tobbenb — CHANGES_REQUESTED** [review]
You do not touch the package-versions.txt. It's only updated by Jenkins. If you want to add a package, you have to do it in all of the 3 dockerfiles. You also didn't add anything to the changelog in the readme-vars file. So either close this PR and make a new or change this one.

You can always build the container locally. It's easy.
Execute the below command in the webgrabplus source folder.

`
docker build -t webgrabplus .
`

**Comment by pbathuk** [comment]
brilliant, thanks for the heads up. I am just compiling the new build on my local machine to confirm it works and will then push a change. sorry about that. mis understood how jenkins & the build process works & made the wrong assumption

**Comment by pbathuk** [comment]
I have fully tested the above & assuming it has worked as expected resolves the issue and does not break the docker.

**Comment by pbathuk** [comment]
Am I best closing this PR and restarting? I don't get what the error is on the CI jenkins Details sorry

**Comment by Roxedus** [comment]
GHCR is currently doing maintenance, a new PR wont change that. Just be patient until they are done.

**Comment by pbathuk** [comment]
@Roxedus thanks.
Use GitHub for work, but not the checks side so not 100% how it works. Good to know its not me haha

**Comment by pbathuk** [comment]
I was just wondering if this required more attention or changes?

**Review by tobbenb — APPROVED** [review]

**Pull request merged**
